# Generated by Django 3.1.3 on 2020-11-18 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
