# Generated by Django 3.1.3 on 2020-11-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SongsApp', '0002_song_song_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_description',
            field=models.CharField(max_length=255),
        ),
    ]
